services:
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscriber
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest